type = "webpack"
workers_dev = false
account_id = "f4f23e22f7e77a59462ef50a69cc232a"

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
name = "lifeinthecloud-website-production"
route = "lifeinthecloud.fr/*"
