name: Deploy site to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm modules
        uses: c-hive/gha-npm-cache@v1
      - name: Npm install
        run: npm install
      - name: Publish on cloudflare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
